### ISSUE TITLE
rederect url 默认是localhost 显示参数错误

### ISSUE THREAD

**Issue by zhangxiaocong** [wkl007/vue-wechat-login#5]
rederect url 默认是localhost 
登陆显示参数错误
https://open.weixin.qq.com/connect/oauth2/authorize?appid=wxa662030865c7d7aa&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2F&response_type=code&scope=snsapi_userinfo&state=3z4k0obbg239vh79isw6gm&uin=MTMwNjM4MTMzOQ%3D%3D&key=1250b4fb74031a210c8d4fb3585216235041ad669ea47150ccbfd36ec23baad480efe134447a2b5ff184d00df47ac052&pass_ticket=hzxpzpmNMkNUacT2WSHZE4uMZD1Z1l2pkwpL6BVwSmV2XQx53IMYSxRz4Bwh5ZAON/2yBRivZ989eLtpKQIPvg==

**Comment by zhangxiaocong** [comment]
redirect_url改成域名 不起作用

**Comment by wkl007** [comment]
这个得放在微信环境下使用，localhost不生效
