### ISSUE TITLE
npm run serve 报错？

### ISSUE THREAD

**Issue by spiritelf** [wkl007/vue-wechat-login#7]
ERROR  Error: No files matching the pattern "E:\黄钦\前端\vue-wechat-login-vue_2.0\src\**\*.{vue,htm,html,css,sss,less,scss}" were found.
Error: No files matching the pattern "E:\黄钦\前端\vue-wechat-login-vue_2.0\src\**\*.{vue,htm,html,css,sss,less,scss}" were found.
    at E:\黄钦\前端\vue-wechat-login-vue_2.0\node_modules\stylelint\lib\standalone.js:212:12
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-wechat-login@0.1.0 build:dev: `vue-cli-service build --mode dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-wechat-login@0.1.0 build:dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\huang\AppData\Roaming\npm-cache\_logs\2020-11-16T02_25_26_868Z-debug.log

**Comment by wkl007** [comment]
测试了一下用`cnpm`安装会报错，建议使用`yarn`进行安装
